version: "3.5"
services:

  emaildb_example:
    image: renatocron/email-db-service:latest
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./
    volumes:
      - ./data-emaildb/:/data/
    networks:
      - yourdbnetwork

networks:
  yourdbnetwork:
